import { ArrowRight, Search } from "lucide-react";
import { articles, categories, products, site } from "@/data/catalog";
import { BrandMark } from "@/components/brand-mark";

export default function HomePage() {
  return <main>
    <div className="trend-bar">The considered edit for style and everyday life</div>
    <header className="site-header"><BrandMark /><nav>{categories.map((category) => <a href={`/categories/${category.slug}`} key={category.slug}>{category.name}</a>)}</nav><a className="search" href="/search" aria-label="Search VogueGlows"><Search size={18} /></a></header>
    <section className="home-hero"><div><p>Independent shopping guides</p><h1>Beautiful choices, with the useful details intact.</h1><span>VogueGlows covers style and everyday life with practical buying context before any merchant recommendation is published.</span><a href="#latest">Explore the edit <ArrowRight size={16} /></a></div><img src="/images/vg-hero-still-life.png" alt="Sunlit gallery still life with a black tote and ivory linen" /></section>
    <section className="category-rail"><div className="rail-title"><h2>Browse by category</h2><a href="#latest">See the latest <ArrowRight size={16} /></a></div><div className="category-grid category-grid-all">{categories.map((category) => <a href={`/categories/${category.slug}`} className="category-tile" key={category.slug}><img src={category.image} alt="" /><h3>{category.name}</h3><p>{category.description}</p></a>)}</div></section>
    <section className="product-section" id="latest"><div className="section-heading"><p>Buying guides</p><h2>Start with the details that decide the fit.</h2><span>These guides explain what to check before choosing a product. Merchant recommendations are added only after the listing, terms, and destination have been reviewed.</span></div><div className="product-grid product-grid-text">{products.map((product, index) => <article className="product-card" key={product.slug}><i>0{index + 1}</i><p>{categories.find((category) => category.slug === product.category)?.name}</p><h3><a href={`/products/${product.slug}`}>{product.name}</a></h3><span>{product.summary}</span><a className="text-link" href={`/products/${product.slug}`}>Open guide <ArrowRight size={15} /></a></article>)}</div></section>
    <section className="content-area"><div><div className="section-heading compact"><p>Journal</p><h2>Read before you buy.</h2></div>{articles.map((article, index) => <a className="article-row" href={`/journal/${article.slug}`} key={article.slug}><b>0{index + 1}</b><div><p>{article.category}</p><h3>{article.title}</h3><span>{article.excerpt}</span><strong>Read more <ArrowRight size={13} /></strong></div></a>)}</div><aside><div className="side-card"><p>OUR APPROACH</p><h2>Useful context,<br />plainly stated.</h2><span>We distinguish source-backed product facts from editorial guidance and place commercial disclosures where readers can see them.</span><a href="/info/about">How we work <ArrowRight size={15} /></a></div></aside></section>
    <footer><BrandMark inverted /><p>{site.affiliateNotice}</p><div><a href="/info/about">About</a><a href="/info/contact">Contact</a><a href="/info/privacy">Privacy</a><a href="/info/terms">Terms</a><a href="/info/disclosure">Disclosure</a><a href="/info/cookie-notice">Cookies</a></div></footer>
  </main>;
}
