import { ArrowRight } from "lucide-react";
import { articles, categories, products } from "@/data/catalog";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";

export default function HomePage() {
  return <main>
    <div className="trend-bar">An independent journal for style and everyday life</div>
    <SiteHeader active="home" />
    <section className="home-hero"><div><p>VogueGlows Journal</p><h1>Clothes, bags, beauty, and the pieces that stay in rotation.</h1><span>Personal notes and carefully sourced product profiles for getting dressed, caring for skin, and traveling with less guesswork.</span><a href="/journal">Read the journal <ArrowRight size={16} /></a></div><img src="/images/vg-hero-still-life.webp" alt="Sunlit gallery still life with a black tote and ivory linen" fetchPriority="high" decoding="async" /></section>
    <section className="featured-stories" id="featured"><div className="section-heading"><p>From the journal</p><h2>Three notes to begin with.</h2><span>For a purchase, a packing list, or the next outfit decision.</span></div><div className="featured-grid">{articles.map((article) => <a className="featured-card" href={`/journal/${article.slug}`} key={article.slug}><img src={article.image} alt="" loading="lazy" decoding="async" /><p>{article.category}</p><h3>{article.title}</h3><span>{article.excerpt}</span><b>Read article <ArrowRight size={14} /></b></a>)}</div></section>
    <section className="editor-note"><div><p>A useful edit</p><h2>The details that make an ordinary purchase easier.</h2></div><div><p>A blazer has to work with the layers already in the wardrobe. A shoulder bag has to hold the things carried every day. A moisturizer has to fit the rest of a routine. Those practical details are where each edit begins.</p><a className="text-link" href="/info/about">How VogueGlows works <ArrowRight size={15} /></a></div></section>
    <section className="category-rail"><div className="rail-title"><h2>Browse by what you are looking for.</h2><a href="/trends">See all shopping notes <ArrowRight size={16} /></a></div><div className="category-grid category-grid-all">{categories.map((category) => <a href={`/categories/${category.slug}`} className="category-tile" key={category.slug}><img src={category.image} alt="" loading="lazy" decoding="async" /><h3>{category.name}</h3><p>{category.description}</p></a>)}</div></section>
    <section className="product-section" id="latest"><div className="section-heading"><p>The Edit</p><h2>Current product profiles, checked at the source.</h2><span>Each profile now leads to a real US brand or retailer page. Affiliate tracking is disclosed only where it is actually used.</span></div><div className="product-grid product-grid-text">{products.map((product) => <article className="product-card" key={product.slug}><p>{categories.find((category) => category.slug === product.category)?.name}</p><h3><a href={`/products/${product.slug}`}>{product.name}</a></h3><span>{product.summary}</span><a className="text-link" href={`/products/${product.slug}`}>Read profile <ArrowRight size={15} /></a></article>)}</div><div className="edit-link"><a href="/trends">Browse The Edit <ArrowRight size={15} /></a></div></section>
    <SiteFooter />
  </main>;
}
